import { db } from "./index";
import { members, organizations } from "./schema";
import { and, eq, sql } from "drizzle-orm";
import type { ExtractTablesWithRelations } from "drizzle-orm";
import type { PgTransaction } from "drizzle-orm/pg-core";
import type { PostgresJsQueryResultHKT } from "drizzle-orm/postgres-js";
import * as schema from "./schema";

export type TenantTransaction = PgTransaction<
  PostgresJsQueryResultHKT, 
  typeof schema, 
  ExtractTablesWithRelations<typeof schema>
>;

/**
 * getTenantDb
 * 
 * The core utility for Hardenend Multi-Tenancy.
 * 
 * 1. Validates that the userId actually belongs to the organization (Rule 1).
 * 2. Sets the PostgreSQL search_path to the tenant's schema.
 * 3. Returns a Drizzle instance restricted to that context.
 * 
 * @param userId - The ID of the user making the request (from session).
 * @param organizationId - The target organization ID.
 */
export async function getTenantDb<T>(
  userId: string,
  organizationId: string,
  callback: (tx: TenantTransaction) => Promise<T>
): Promise<T> {
  // 1. Pre-flight Membership check (Rule 1: Schema-Owner Validation)
  // We query the public schema to verify if this user is a member of the org.
  const member = await db.query.members.findFirst({
    where: and(
      eq(members.userId, userId),
      eq(members.organizationId, organizationId)
    ),
    with: {
      organization: true
    }
  });

  if (!member || !member.organization.tenantSchemaName) {
    throw new Error("Access Denied: You are not a member of this organization.");
  }

  const tenantSchema = member.organization.tenantSchemaName;

  /**
   * 2. Transaction-level Isolation
   * 
   * We use a transaction to ensure that the 'SET search_path' only affects 
   * the current connection for the duration of the query callback.
   */
  return await db.transaction(async (tx) => {
    // Set search_path to prioritize tenant schema, fallback to public
    // We use sql.raw because schema names are generated by the system (tenant_...)
    await tx.execute(sql.raw(`SET search_path TO ${tenantSchema}, public`));
    
    // Execute the business logic within this isolated context
    return await callback(tx);
  });
}

/**
 * Administrative bypass for getTenantDb (use with CAUTION)
 * Only for background jobs or migrations where no User is present.
 */
export async function withAdminTenantDb<T>(
  organizationId: string,
  callback: (tx: TenantTransaction) => Promise<T>
): Promise<T> {
  const org = await db.query.organizations.findFirst({
    where: eq(organizations.id, organizationId),
  });

  if (!org || !org.tenantSchemaName) {
    throw new Error("Organization or tenant schema not found.");
  }

  return await db.transaction(async (tx) => {
    await tx.execute(sql.raw(`SET search_path TO ${org.tenantSchemaName}, public`));
    return await callback(tx);
  });
}
