import crypto from "crypto";
import jwt from "jsonwebtoken";

const ALGORITHM = "aes-256-gcm";
const SECRET = process.env.CONNECTOR_SECRET || process.env.ENCRYPTION_KEY || "default-connector-secret-key-placeholder-32-bytes";
const KEY = crypto.scryptSync(SECRET, "connector-salt", 32);

/**
 * Encrypts a plaintext string using AES-256-GCM.
 * Returns formatted string as: ivHex:authTagHex:encryptedHex
 */
export function encrypt(text: string): string {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGORITHM, KEY, iv);
  
  let encrypted = cipher.update(text, "utf8", "hex");
  encrypted += cipher.final("hex");
  
  const authTag = cipher.getAuthTag().toString("hex");
  
  return `${iv.toString("hex")}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a ciphertext string generated by the encrypt function.
 */
export function decrypt(encryptedText: string): string {
  const [ivHex, authTagHex, encrypted] = encryptedText.split(":");
  if (!ivHex || !authTagHex || !encrypted) {
    throw new Error("Invalid encrypted text format");
  }

  const iv = Buffer.from(ivHex, "hex");
  const authTag = Buffer.from(authTagHex, "hex");
  const decipher = crypto.createDecipheriv(ALGORITHM, KEY, iv);
  
  decipher.setAuthTag(authTag);
  
  let decrypted = decipher.update(encrypted, "hex", "utf8");
  decrypted += decipher.final("utf8");
  
  return decrypted;
}

/**
 * Generates a signed, short-lived JWT token to secure OAuth state.
 */
export function generateStateToken(userId: string, orgId: string): string {
  return jwt.sign({ userId, orgId }, SECRET, { expiresIn: "15m" });
}

/**
 * Verifies a signed OAuth state JWT token and returns payload.
 */
export function verifyStateToken(token: string): { userId: string; orgId: string } {
  try {
    const payload = jwt.verify(token, SECRET) as { userId: string; orgId: string };
    if (!payload.userId || !payload.orgId) {
      throw new Error("Invalid state token payload structure");
    }
    return payload;
  } catch (error) {
    console.error("Failed to verify state token:", error);
    throw new Error("Invalid state token");
  }
}
